# Generated by Django 5.0.4 on 2024-08-20 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationMainCaregoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(max_length=200, verbose_name="دسته اصلی"),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=400,
                        unique=True,
                        verbose_name="اسلاگ",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال/غیرفعال"),
                ),
            ],
            options={
                "verbose_name": "دسته اصلی",
                "verbose_name_plural": "دسته های اصلی",
            },
        ),
        migrations.CreateModel(
            name="AppsHelpModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان آموزش")),
                ("description", models.TextField(verbose_name="توضیح آموزش")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=400,
                        unique=True,
                        verbose_name="اسلاگ",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="منشر شود؟"),
                ),
            ],
            options={
                "verbose_name": "آموزش",
                "verbose_name_plural": "آموزش ها",
            },
        ),
        migrations.CreateModel(
            name="ApplicationImporterModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "google_play_id",
                    models.CharField(max_length=200, verbose_name="آیدی google play"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ناشر",
                    ),
                ),
            ],
            options={
                "verbose_name": "ایمپورتر",
                "verbose_name_plural": "ایمپورتر",
            },
        ),
        migrations.CreateModel(
            name="ApplicationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                (
                    "group",
                    models.CharField(
                        choices=[("1", "برنامه"), ("2", "بازی")],
                        max_length=50,
                        verbose_name="گروه",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=400,
                        unique=True,
                        verbose_name="اسلاگ",
                    ),
                ),
                (
                    "link_description",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="توضیحات بالای لینک",
                    ),
                ),
                (
                    "link_information",
                    models.TextField(
                        blank=True, null=True, verbose_name="توضیحات زیر لینک"
                    ),
                ),
                ("update", models.DateTimeField(verbose_name="تاریخ به روزرسانی")),
                (
                    "version",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="نسخه"
                    ),
                ),
                (
                    "android_version",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="نسخه مورد نیاز",
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="توضیحات سئو",
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="محتوا"),
                ),
                (
                    "price",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="قیمت در استور",
                    ),
                ),
                (
                    "creator",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="سازنده"
                    ),
                ),
                (
                    "score",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="امتیاز"
                    ),
                ),
                (
                    "download_count",
                    models.PositiveIntegerField(
                        blank=True, default=0, null=True, verbose_name="تعداد دانلود"
                    ),
                ),
                (
                    "ages",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="رده سنی"
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="سایز"
                    ),
                ),
                (
                    "icon",
                    models.ImageField(upload_to="images/icons/", verbose_name="آیکون"),
                ),
                ("is_update", models.BooleanField(default=False, verbose_name="آپدیت")),
                (
                    "is_online",
                    models.BooleanField(default=False, verbose_name="آنلاین"),
                ),
                ("is_new", models.BooleanField(default=False, verbose_name="جدید")),
                ("is_mod", models.BooleanField(default=False, verbose_name="مود")),
                ("is_free", models.BooleanField(default=False, verbose_name="رایگان")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="منتشر شود؟"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ناشر",
                    ),
                ),
                (
                    "main_caregory",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="applications.applicationmaincaregorymodel",
                        verbose_name="دسته اصلی",
                    ),
                ),
            ],
            options={
                "verbose_name": "نرم افزار",
                "verbose_name_plural": "نرم افزارها",
            },
        ),
        migrations.CreateModel(
            name="ApplicationLinkModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="متن دکمه")),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("s-green", "سبز"),
                            ("s-yellow", "زرد"),
                            ("s-red", "قرمز"),
                            ("s-blue", "آبی"),
                        ],
                        default="s-green",
                        max_length=200,
                        verbose_name="رنگ دکمه",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=400, unique=True, verbose_name="اسلاگ"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="files/",
                        verbose_name="فایل برنامه",
                    ),
                ),
                ("volume", models.CharField(max_length=200, verbose_name="حجم")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="غعال/غیرغعال"),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.applicationmodel",
                        verbose_name="برنامه",
                    ),
                ),
            ],
            options={
                "verbose_name": "لینک",
                "verbose_name_plural": "لینک ها",
            },
        ),
        migrations.CreateModel(
            name="ApplicationScreenShotModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان تصویر")),
                (
                    "screenshot",
                    models.ImageField(
                        upload_to="images/screenshots/", verbose_name="اسکرین شات"
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.applicationmodel",
                        verbose_name="برنامه",
                    ),
                ),
            ],
            options={
                "verbose_name": "اسکریت شات",
                "verbose_name_plural": "اسکرین شات ها",
            },
        ),
        migrations.CreateModel(
            name="AppRequestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_link", models.URLField(verbose_name="لینک برنامه")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="درخواست کننده",
                    ),
                ),
            ],
            options={
                "verbose_name": "درخواست برنامه",
                "verbose_name_plural": "درخواست های برنامه",
            },
        ),
        migrations.CreateModel(
            name="AppsCommentsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت"),
                ),
                ("text", models.TextField(verbose_name="متن نظر")),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="منتشر شود؟"),
                ),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.applicationmodel",
                        verbose_name="نرم افزار",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.appscommentsmodel",
                        verbose_name="والد",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "نظر برنامه",
                "verbose_name_plural": "نظرات برنامه ها",
            },
        ),
        migrations.CreateModel(
            name="AppsCommentsLikeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="ایپی کاربر"
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.appscommentsmodel",
                        verbose_name="کامنت",
                    ),
                ),
            ],
            options={
                "verbose_name": "لایک کامنت",
                "verbose_name_plural": "لایک های کامنت",
            },
        ),
        migrations.CreateModel(
            name="AppsCommentsDisLikeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="ایپی کاربر"
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.appscommentsmodel",
                        verbose_name="کامنت",
                    ),
                ),
            ],
            options={
                "verbose_name": "دیسلایک کامنت",
                "verbose_name_plural": "دیسلایک های کامنت",
            },
        ),
        migrations.CreateModel(
            name="AppsDisLikesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="ایپی کاربر"
                    ),
                ),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.applicationmodel",
                        verbose_name="نرم افزار",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "دیسلایک",
                "verbose_name_plural": "دیسلایک ها",
            },
        ),
        migrations.CreateModel(
            name="AppsLikesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="ایپی کاربر"
                    ),
                ),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.applicationmodel",
                        verbose_name="نرم افزار",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "لایک",
                "verbose_name_plural": "لایک ها",
            },
        ),
        migrations.CreateModel(
            name="SuggestedAppsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="منتشر شود؟"),
                ),
                (
                    "suggestion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.applicationmodel",
                        verbose_name="نرم افزار های پیشنهادی",
                    ),
                ),
            ],
            options={
                "verbose_name": "نرم افزار پیشنهادی",
                "verbose_name_plural": "نرم افزارهای پیشنهادی",
            },
        ),
    ]
