# Generated by Django 5.0.4 on 2024-05-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FooterModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "copyright",
                    models.CharField(max_length=255, verbose_name="متن کپی رایت"),
                ),
                (
                    "telegram_url",
                    models.URLField(blank=True, null=True, verbose_name="لینک تلگرام"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال/غیرفعال"),
                ),
            ],
            options={
                "verbose_name": "فوتر",
                "verbose_name_plural": "فوتر",
            },
        ),
        migrations.CreateModel(
            name="LogoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logo", models.ImageField(upload_to="logo/")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال/غیر فعال"),
                ),
            ],
            options={
                "verbose_name": "لوگو",
                "verbose_name_plural": "لوگوها",
            },
        ),
    ]
